export const students = [
  {
    id: 1,
    name: "Student 1",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 2,
    name: "Student 2",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 3,
    name: "Student 3",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 4,
    name: "Student 4",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 5,
    name: "Student 5",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 6,
    name: "Student 6",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 7,
    name: "Student 7",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 8,
    name: "Student 8",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 9,
    name: "Student 9",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 10,
    name: "Student 10",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 11,
    name: "Student 11",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 12,
    name: "Student 12",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 13,
    name: "Student 13",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
  {
    id: 14,
    name: "Student 14",
    mentorId: null,
    ideation: 0,
    execution: 0,
    viva: 0,
    total: 0,
  },
];

export const mentors = [
  { id: 1, name: "Mentor 1" },
  { id: 2, name: "Mentor 2" },
  { id: 3, name: "Mentor 3" },
  { id: 4, name: "Mentor 4" },
  { id: 5, name: "Mentor 5" },
  { id: 6, name: "Mentor 6" },
  { id: 7, name: "Mentor 7" },
  { id: 8, name: "Mentor 8" },
  { id: 9, name: "Mentor 9" },
  { id: 10, name: "Mentor 10" },
];
